M48
; DRILL file {KiCad (6.0.4)} date Mon Jun  6 09:07:41 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-06T09:07:41-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X5.0971Y-2.1986
X5.0971Y-2.297
X5.294Y-2.4939
X5.4909Y-2.1986
X5.4909Y-2.297
T0
M30
