M48
; DRILL file {KiCad (6.0.4)} date Thu Apr 28 21:29:08 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-28T21:29:08-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X7.1102Y-2.4016
X7.1102Y-2.5
X7.3071Y-2.6969
X7.5039Y-2.4016
X7.5039Y-2.5
T0
M30
